INSERT INTO ADDRESS(ADDRESS_ID) VALUES ( 1);

INSERT INTO CUSTOMER(CUSTOMER_ID) VALUES ( 1 );

INSERT INTO PRODUCT(PRODUCT_ID,NAME,PRICE,TYPE) VALUES (1,'Product 1',15.0,'BOOK');
INSERT INTO PRODUCT(PRODUCT_ID,NAME,PRICE,TYPE) VALUES (2,'Product 2',15.0,'BOOK');

INSERT INTO ORDR(ORDR_ID,CLOSED_AT,ADDRESS_ID,CUSTOMER_ID) VALUES (1,null,1,1);
INSERT INTO ORDERITEM(ID,QUANTITY,ORDR_ID,PRODUCT_ID) VALUES (1,1,1,1);
INSERT INTO ORDERITEM(ID,QUANTITY,ORDR_ID,PRODUCT_ID) VALUES (2,2,1,2);
